version: '3.1'

services:
  db:
    image: mysql:8.0.39
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db_essia

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

volumes:
  dbbase:

